//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartUSKit_CS.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartUSKit_CS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 腹部 的本地化字符串。
        /// </summary>
        public static string Abdomen {
            get {
                return ResourceManager.GetString("Abdomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加默认 的本地化字符串。
        /// </summary>
        public static string AddDefault {
            get {
                return ResourceManager.GetString("AddDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加该模板 的本地化字符串。
        /// </summary>
        public static string AddThisTemplate {
            get {
                return ResourceManager.GetString("AddThisTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年龄： 的本地化字符串。
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校正角度 的本地化字符串。
        /// </summary>
        public static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Back1 {
            get {
                return ResourceManager.GetString("Back1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基线 的本地化字符串。
        /// </summary>
        public static string BaseLine {
            get {
                return ResourceManager.GetString("BaseLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        public static string BiopsyClear {
            get {
                return ResourceManager.GetString("BiopsyClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增强 的本地化字符串。
        /// </summary>
        public static string BiopsyEnhance {
            get {
                return ResourceManager.GetString("BiopsyEnhance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平面内 的本地化字符串。
        /// </summary>
        public static string BiopsyInPlane {
            get {
                return ResourceManager.GetString("BiopsyInPlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平面外 的本地化字符串。
        /// </summary>
        public static string BiopsyOutPlane {
            get {
                return ResourceManager.GetString("BiopsyOutPlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出生日期: 的本地化字符串。
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 乳腺 的本地化字符串。
        /// </summary>
        public static string Breast {
            get {
                return ResourceManager.GetString("Breast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法访问服务器 的本地化字符串。
        /// </summary>
        public static string CannotConnetToServer {
            get {
                return ResourceManager.GetString("CannotConnetToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 心脏 的本地化字符串。
        /// </summary>
        public static string Cardiac {
            get {
                return ResourceManager.GetString("Cardiac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颈动脉 的本地化字符串。
        /// </summary>
        public static string Carotid {
            get {
                return ResourceManager.GetString("Carotid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请连接设备 的本地化字符串。
        /// </summary>
        public static string ConnectedToDevice {
            get {
                return ResourceManager.GetString("ConnectedToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建病例 的本地化字符串。
        /// </summary>
        public static string CreateNewCase {
            get {
                return ResourceManager.GetString("CreateNewCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这将会删除目前设置的信息 的本地化字符串。
        /// </summary>
        public static string DeleteExamInfo {
            get {
                return ResourceManager.GetString("DeleteExamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传后删除本地文件 的本地化字符串。
        /// </summary>
        public static string DeleteFilesAfterUpload {
            get {
                return ResourceManager.GetString("DeleteFilesAfterUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除选中页 的本地化字符串。
        /// </summary>
        public static string DeleteSelectedPage {
            get {
                return ResourceManager.GetString("DeleteSelectedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string DeleteSuccessful {
            get {
                return ResourceManager.GetString("DeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深度- 的本地化字符串。
        /// </summary>
        public static string DepthDecrease {
            get {
                return ResourceManager.GetString("DepthDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深度+ 的本地化字符串。
        /// </summary>
        public static string DepthIncrease {
            get {
                return ResourceManager.GetString("DepthIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查医生 的本地化字符串。
        /// </summary>
        public static string DiagDoc {
            get {
                return ResourceManager.GetString("DiagDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只作临床参考，不作证明材料 的本地化字符串。
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 距离 的本地化字符串。
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查医师 的本地化字符串。
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查 的本地化字符串。
        /// </summary>
        public static string Examination {
            get {
                return ResourceManager.GetString("Examination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 凸阵 的本地化字符串。
        /// </summary>
        public static string ExaminationConvex {
            get {
                return ResourceManager.GetString("ExaminationConvex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查时间 的本地化字符串。
        /// </summary>
        public static string ExaminationDate {
            get {
                return ResourceManager.GetString("ExaminationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线阵 的本地化字符串。
        /// </summary>
        public static string ExaminationLinear {
            get {
                return ResourceManager.GetString("ExaminationLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查号 的本地化字符串。
        /// </summary>
        public static string ExamNO {
            get {
                return ResourceManager.GetString("ExamNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 女 的本地化字符串。
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤 的本地化字符串。
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 血流模式 的本地化字符串。
        /// </summary>
        public static string FlowMode {
            get {
                return ResourceManager.GetString("FlowMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 妇科 的本地化字符串。
        /// </summary>
        public static string Gynecology {
            get {
                return ResourceManager.GetString("Gynecology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 心跳： 的本地化字符串。
        /// </summary>
        public static string Heartbeat {
            get {
                return ResourceManager.GetString("Heartbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 心率 的本地化字符串。
        /// </summary>
        public static string HeartRate {
            get {
                return ResourceManager.GetString("HeartRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医院 的本地化字符串。
        /// </summary>
        public static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医院名称设置 的本地化字符串。
        /// </summary>
        public static string HospitalName {
            get {
                return ResourceManager.GetString("HospitalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号： 的本地化字符串。
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证号 的本地化字符串。
        /// </summary>
        public static string IDNO {
            get {
                return ResourceManager.GetString("IDNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 肾脏 的本地化字符串。
        /// </summary>
        public static string Kidney {
            get {
                return ResourceManager.GetString("Kidney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 肺 的本地化字符串。
        /// </summary>
        public static string Lung {
            get {
                return ResourceManager.GetString("Lung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 男 的本地化字符串。
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最多输入4组测量 的本地化字符串。
        /// </summary>
        public static string MaxMeasureCount {
            get {
                return ResourceManager.GetString("MaxMeasureCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 腹围 的本地化字符串。
        /// </summary>
        public static string Meas_info_AC {
            get {
                return ResourceManager.GetString("Meas_info_AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角度 的本地化字符串。
        /// </summary>
        public static string Meas_info_ANGLE {
            get {
                return ResourceManager.GetString("Meas_info_ANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 面积 的本地化字符串。
        /// </summary>
        public static string Meas_info_AREA {
            get {
                return ResourceManager.GetString("Meas_info_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胎重(双顶径) 的本地化字符串。
        /// </summary>
        public static string Meas_info_BPD_EFW {
            get {
                return ResourceManager.GetString("Meas_info_BPD_EFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周长 的本地化字符串。
        /// </summary>
        public static string Meas_info_CIRCUM {
            get {
                return ResourceManager.GetString("Meas_info_CIRCUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预产期 的本地化字符串。
        /// </summary>
        public static string Meas_info_EDD {
            get {
                return ResourceManager.GetString("Meas_info_EDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胎重(股骨长) 的本地化字符串。
        /// </summary>
        public static string Meas_info_FL_EFW {
            get {
                return ResourceManager.GetString("Meas_info_FL_EFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 孕龄 的本地化字符串。
        /// </summary>
        public static string Meas_info_GA {
            get {
                return ResourceManager.GetString("Meas_info_GA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双顶径 的本地化字符串。
        /// </summary>
        public static string Meas_info_GA_BPD {
            get {
                return ResourceManager.GetString("Meas_info_GA_BPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头臀长 的本地化字符串。
        /// </summary>
        public static string Meas_info_GA_CRL {
            get {
                return ResourceManager.GetString("Meas_info_GA_CRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 股骨长 的本地化字符串。
        /// </summary>
        public static string Meas_info_GA_FL {
            get {
                return ResourceManager.GetString("Meas_info_GA_FL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 孕囊直径 的本地化字符串。
        /// </summary>
        public static string Meas_info_GA_GS {
            get {
                return ResourceManager.GetString("Meas_info_GA_GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头围 的本地化字符串。
        /// </summary>
        public static string Meas_info_GA_HC {
            get {
                return ResourceManager.GetString("Meas_info_GA_HC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        public static string Meas_info_LENGTH {
            get {
                return ResourceManager.GetString("Meas_info_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 腹围 的本地化字符串。
        /// </summary>
        public static string MeasureAC {
            get {
                return ResourceManager.GetString("MeasureAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角度 的本地化字符串。
        /// </summary>
        public static string MeasureAngle {
            get {
                return ResourceManager.GetString("MeasureAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 面积/周长 的本地化字符串。
        /// </summary>
        public static string MeasureAreaCir {
            get {
                return ResourceManager.GetString("MeasureAreaCir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双顶径 的本地化字符串。
        /// </summary>
        public static string MeasureBPD {
            get {
                return ResourceManager.GetString("MeasureBPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胎重(双顶径) 的本地化字符串。
        /// </summary>
        public static string MeasureBPD_EFW {
            get {
                return ResourceManager.GetString("MeasureBPD_EFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头臀长 的本地化字符串。
        /// </summary>
        public static string MeasureCRL {
            get {
                return ResourceManager.GetString("MeasureCRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胎重 的本地化字符串。
        /// </summary>
        public static string MeasureEFW {
            get {
                return ResourceManager.GetString("MeasureEFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 股骨长 的本地化字符串。
        /// </summary>
        public static string MeasureFL {
            get {
                return ResourceManager.GetString("MeasureFL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胎重(股骨长) 的本地化字符串。
        /// </summary>
        public static string MeasureFL_EFW {
            get {
                return ResourceManager.GetString("MeasureFL_EFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 孕囊直径 的本地化字符串。
        /// </summary>
        public static string MeasureGSD {
            get {
                return ResourceManager.GetString("MeasureGSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头围 的本地化字符串。
        /// </summary>
        public static string MeasureHC {
            get {
                return ResourceManager.GetString("MeasureHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 心率(2) 的本地化字符串。
        /// </summary>
        public static string MeasureHeartRate2 {
            get {
                return ResourceManager.GetString("MeasureHeartRate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        public static string MeasureLength {
            get {
                return ResourceManager.GetString("MeasureLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨迹 的本地化字符串。
        /// </summary>
        public static string MeasureTrace {
            get {
                return ResourceManager.GetString("MeasureTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 速度 的本地化字符串。
        /// </summary>
        public static string MeasureVelocity {
            get {
                return ResourceManager.GetString("MeasureVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量中... 的本地化字符串。
        /// </summary>
        public static string Measuring {
            get {
                return ResourceManager.GetString("Measuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动 的本地化字符串。
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 肌骨 的本地化字符串。
        /// </summary>
        public static string Msk {
            get {
                return ResourceManager.GetString("Msk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名： 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名中不可包含符号！ 的本地化字符串。
        /// </summary>
        public static string NameCannotContainsCharacters {
            get {
                return ResourceManager.GetString("NameCannotContainsCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 神经 的本地化字符串。
        /// </summary>
        public static string Nerve {
            get {
                return ResourceManager.GetString("Nerve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到可用网卡！ 的本地化字符串。
        /// </summary>
        public static string NoAvailableNetworkAdapter {
            get {
                return ResourceManager.GetString("NoAvailableNetworkAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产科 的本地化字符串。
        /// </summary>
        public static string Obstertric {
            get {
                return ResourceManager.GetString("Obstertric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关 的本地化字符串。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开 的本地化字符串。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他 的本地化字符串。
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 病例信息 的本地化字符串。
        /// </summary>
        public static string PatientInformation {
            get {
                return ResourceManager.GetString("PatientInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 病人姓名不可为空！ 的本地化字符串。
        /// </summary>
        public static string PatientNameCannotbBeEmpty {
            get {
                return ResourceManager.GetString("PatientNameCannotbBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 病例管理 的本地化字符串。
        /// </summary>
        public static string PatientsManage {
            get {
                return ResourceManager.GetString("PatientsManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 儿科 的本地化字符串。
        /// </summary>
        public static string Pediatrics {
            get {
                return ResourceManager.GetString("Pediatrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申请医师 的本地化字符串。
        /// </summary>
        public static string Physician {
            get {
                return ResourceManager.GetString("Physician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近检查 的本地化字符串。
        /// </summary>
        public static string RecentExamination {
            get {
                return ResourceManager.GetString("RecentExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回放帧数 的本地化字符串。
        /// </summary>
        public static string ReplayFrames {
            get {
                return ResourceManager.GetString("ReplayFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报告 的本地化字符串。
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超声所见 的本地化字符串。
        /// </summary>
        public static string ReportObs {
            get {
                return ResourceManager.GetString("ReportObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报告模板 的本地化字符串。
        /// </summary>
        public static string ReportTemplates {
            get {
                return ResourceManager.GetString("ReportTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超声提示 的本地化字符串。
        /// </summary>
        public static string ReportTips {
            get {
                return ResourceManager.GetString("ReportTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申请医生 的本地化字符串。
        /// </summary>
        public static string ReqDoc {
            get {
                return ResourceManager.GetString("ReqDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复位 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请重新启动设备以使更改生效 的本地化字符串。
        /// </summary>
        public static string RestartAndReconnect {
            get {
                return ResourceManager.GetString("RestartAndReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已保存的图片 的本地化字符串。
        /// </summary>
        public static string SavedImage {
            get {
                return ResourceManager.GetString("SavedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存病人数据 的本地化字符串。
        /// </summary>
        public static string SavePatientData {
            get {
                return ResourceManager.GetString("SavePatientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择病例 的本地化字符串。
        /// </summary>
        public static string SelectPatient {
            get {
                return ResourceManager.GetString("SelectPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别： 的本地化字符串。
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示信息 的本地化字符串。
        /// </summary>
        public static string ShowInformation {
            get {
                return ResourceManager.GetString("ShowInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小器官 的本地化字符串。
        /// </summary>
        public static string Smallparts {
            get {
                return ResourceManager.GetString("Smallparts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻结 的本地化字符串。
        /// </summary>
        public static string StateFreeze {
            get {
                return ResourceManager.GetString("StateFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        public static string StateLive {
            get {
                return ResourceManager.GetString("StateLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回放 的本地化字符串。
        /// </summary>
        public static string StateReplay {
            get {
                return ResourceManager.GetString("StateReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 偏转角度 的本地化字符串。
        /// </summary>
        public static string Steer {
            get {
                return ResourceManager.GetString("Steer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 甲状腺 的本地化字符串。
        /// </summary>
        public static string Thyroid {
            get {
                return ResourceManager.GetString("Thyroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最多添加20张照片 的本地化字符串。
        /// </summary>
        public static string Tip_20Images {
            get {
                return ResourceManager.GetString("Tip_20Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最多只能添加4张图片 的本地化字符串。
        /// </summary>
        public static string Tip_4Images {
            get {
                return ResourceManager.GetString("Tip_4Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经颅 的本地化字符串。
        /// </summary>
        public static string Transcranial {
            get {
                return ResourceManager.GetString("Transcranial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传 的本地化字符串。
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传Dicom文件 的本地化字符串。
        /// </summary>
        public static string UploadDicomFile {
            get {
                return ResourceManager.GetString("UploadDicomFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泌尿系统 的本地化字符串。
        /// </summary>
        public static string Urology {
            get {
                return ResourceManager.GetString("Urology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap USBConnection {
            get {
                object obj = ResourceManager.GetObject("USBConnection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 血管 的本地化字符串。
        /// </summary>
        public static string Vascular {
            get {
                return ResourceManager.GetString("Vascular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 血流量 的本地化字符串。
        /// </summary>
        public static string Vessel {
            get {
                return ResourceManager.GetString("Vessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采样容积 的本地化字符串。
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WiFi信道 的本地化字符串。
        /// </summary>
        public static string WiFiChannel {
            get {
                return ResourceManager.GetString("WiFiChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败 的本地化字符串。
        /// </summary>
        public static string WifiConnectFailed {
            get {
                return ResourceManager.GetString("WifiConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap WIFIConnection {
            get {
                object obj = ResourceManager.GetObject("WIFIConnection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 断开 的本地化字符串。
        /// </summary>
        public static string WiFiDisconnect {
            get {
                return ResourceManager.GetString("WiFiDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放 的本地化字符串。
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
